database_dir:
  /data/metadb/cmdb/fastas_dustmasked
taxonomy_file:
  /data/metadb/cmdb/taxonomy.tsv
hostile_minimap2_index:
  /data/hostile/human-t2t-hla
nohuman_database:
  /data/metadb/nohuman/db
number_database_files:
  400
threads:
  2
threads_align:
  32
sample_name:
  none
sample_list:
  none
read_length:
  151
