taxonomy_file:
  /data/metadb/mihop_taxonomy/taxonomy.tsv
database_dir:
  /data/metadb/mihop_db
hostile_minimap2_index:
  /data/hostile/human-t2t-hla
nohuman_database:
  none
number_database_files:
  423
threads:
  2
threads_align:
  32
sample_name:
  none
sample_list:
  none
read_length:
  151