database_dir:
  /datassd/databases/cmdd_fastas_dustmasked
taxonomy_file:
  /datassd/databases/taxonomy.tsv
hostile_minimap2_index:
  /data/hostile/human-t2t-hla
nohuman_database:
  /datassd/databases/nohuman/db
number_database_files:
  400
threads:
  16
threads_align:
  4
sample_name:
  none
sample_list:
  none
read_length:
  151
gtdb_to_ncbi:
  /datassd/databases/gtdb_to_ncbi.tsv
pathogen_list:
  /datassd/databases/pathogen_list.txt
neg_control_samples:
  auto
