executor: aws-batch
reason: True
keep-going: True
show-failed-logs: True
printshellcmds: True
rerun-incomplete: True
jobs: 500
retries: 1

default_resources:
  runtime: "1h"
  cpus_per_task: 2
  mem_mb: 5000

default-storage-provider: "s3"
